parameters:
#    tshirt_tshirt.example.class: Tshirt\TshirtBundle\Example

services:
#    tshirt_tshirt.example:
#        class: %tshirt_tshirt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
